### ISSUE TITLE
`mobileToDesktop` breaking change between 4.7.3 and 4.8.2?

### ISSUE THREAD

**Issue by panlina** [browserslist/browserslist#431]
`require('browserslist')("cover 90% in CN", { mobileToDesktop: true })` gives `and_chr 78` and other 4 items in 4.7.3, but gives `and_chr 4` and other 4 items in 4.8.2.

We're using `@babel/preset-env` and it broke recently after update. I traced and found `browserslist` gives different result before and after. So I come with the line above. `@babel/preset-env` always calls `browserslist` with `mobileToDesktop: true`. 

Honestly I cannot quite understand how `mobileToDesktop` works from `README.md`, but I found several changes regarding `mobileToDesktop` option between 4.7.3 and 4.8.2. Is current result(4.8.2) correct?

**Comment by ai** [comment]
> require('browserslist')("cover 90% in CN", { mobileToDesktop: true }) gives and_chr 78 and other 4 items in 4.7.3, but gives and_chr 4 and other 4 items in 4.8.2.

We fixed `mobileToDesktop` in a recent update. Why do you think the current output is wrong?

cc @JLHwung

> Honestly I cannot quite understand how mobileToDesktop works from README.md

Can I use has only the latest data for mobile browsers. For instance, there is only `and_chr 78` without `and_chr 77`, `and_chr 76`, etc. As a result `last 3 and_chr versions` will return only `and_chr 78`.

With `mobileToDesktop` we will use `chrome` for `and_chr` to restore that missed versions. `last 3 and_chr versions` will return `and_chr 78, chrome 77, chrome 76`.

**Comment by JLHwung** [comment]
It is a bug of `caniuse-lite`. https://runkit.com/embed/9s4d2o2r0zva

It returns `{ 0: coverage }` for regional `and_chr` browser stats, which means `cover 90% in CN` evaluates to `and_chr 0`.

Before 4.8.1, `and_chr 0` will be interpreted as `and_chr 78` and now interpreted as `and_chr 4`. The latter is also technically incorrect and we may change it to the actual first release of android chrome.

In all, `mobileToDesktop: true` helps catching a bug in `caniuse-lite`.

**Comment by panlina** [comment]
To understand the current situation, do you mean:

* `and_chr 4` is "more correct" than `and_chr 78` and that's why 4.8.1 fixed it
* it's a bug in current version of `caniuse-lite` that is not fixed yet

and I have to avoid using regional query before it's fixed in `caniuse-lite`?

**Comment by ai** [comment]
> In all, mobileToDesktop: true helps catching a bug in caniuse-lite.

Absolutely. I think the problem could be at `caniuse-db` itself since `caniuse-lite` is just repacking.

> It returns { 0: coverage } for regional and_chr browser stats, which means cover 90% in CN evaluates to and_chr 0.

Oh, yeap, it happens often with Can I Use. It is a good solution to replace `0` to the latest version?

**Comment by ai** [comment]
@panlina 

> and_chr 4 is "more correct" than and_chr 78 and that's why 4.8.1 fixed it

Nope, it is just a bug. We had a bug before. Now we see a different result, but it is still a bug. We just need to find the best solution and to fix it.

> it's a bug in current version of caniuse-lite that is not fixed yet

The bug is more likely in `caniuse-db` and it was there a long ago. And it is unlikely that Can I Use will fix it for us. We need to change Browserslist.

**Comment by panlina** [comment]
Thanks, @ai . I'll try to workaround it.

**Comment by max-mykhailenko** [comment]
@panlina  @ai  I still have this problem when use expression like `> 0.9% in my stats`.

**Comment by ai** [comment]
@max-mykhailenko 

1. open new issue
2. show output and expected output

**Comment by max-mykhailenko** [comment]
@ai sure #472 . Thank you!
