### ISSUE TITLE
Cannot --update-db with Yarn on Windows

### ISSUE THREAD

**Issue by twpol** [browserslist/browserslist#531]
It looks like the database updater is sensitive to line endings and, unfortunately for this project, Yarn on Windows has chosen to use Windows line endings:

```
PS REDACTED> yarn browserslist --update-db
yarn run v1.22.5
$ REDACTED\node_modules\.bin\browserslist --update-db
REDACTED\node_modules\browserslist\update-db.js:49
    if (match[1]) return match[1]
             ^

TypeError: Cannot read property '1' of null
    at getCurrentVersion (REDACTED\node_modules\browserslist\update-db.js:49:14)
    at updateDB (REDACTED\node_modules\browserslist\update-db.js:119:17)
    at Object.<anonymous> (REDACTED\node_modules\browserslist\cli.js:40:3)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.
```

If I re-save the `yarn.lock` with LF instead of CRLF, it's fine.

**Comment by ai** [comment]
@twpol Can you help me with fixing RegExp and send PR? I don’t have Windows to test that everything is OK.

**Comment by ai** [comment]
The fix was released in 4.14.2.

**Comment by whmountains** [comment]
Thank you @ai!

I am still experiencing this issue with 4.14.5.  Maybe not the same underlying cause, but identical error message.  I'll let you decide if we should split this into a new issue.

This is on Linux, and I double-checked the line-endings are LF. `browserslist --version` returns `browserslist 4.14.5`.  `yarn --version` returns `1.22.4`.

Running `browserlist --update-db` returns:

```
/home/vagrant/.config/yarn/global/node_modules/browserslist/update-db.js:51
    if (match[1]) return match[1]
             ^

TypeError: Cannot read property '1' of null
    at getCurrentVersion (/home/vagrant/.config/yarn/global/node_modules/browserslist/update-db.js:51:14)
    at updateDB (/home/vagrant/.config/yarn/global/node_modules/browserslist/update-db.js:121:17)
    at Object.<anonymous> (/home/vagrant/.config/yarn/global/node_modules/browserslist/cli.js:40:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
```

Yes, this is inside a Vagrant VM.  I installed it globally because NPX wasn't giving me any stack traces.  Running the command with npx gives the same issue.

**Comment by ai** [comment]
Try `npx browserslist@latest --update-db` to be sure that the latest version was used (`npx` is tricky).

If you still have a problem. Please send PR. I do not have Windows to create a fix.

**Comment by whmountains** [comment]
Same error using the command you requested.  This is MacOS and Linux, not Windows for me.  I would be happy to share the lockfile which is causing the problem.

**Comment by ai** [comment]
@whmountains sure. Can you create a repo to reproduce the problem.

**Comment by BeisiXiong** [comment]
> Try `npx browserslist@latest --update-db` to be sure that the latest version was used (`npx` is tricky).
> 
> If you still have a problem. Please send PR. I do not have Windows to create a fix.

hello, may I ask can I run this command **npx browserslist@latest --update-db** with yarn?

**Comment by ai** [comment]
@BeisiXiong call it with `npx` even if you are using Yarn.

**Comment by BeisiXiong** [comment]
> @BeisiXiong call it with `npx` even if you are using Yarn.

thanks a lot!

**Comment by Petah** [comment]
Was there a solution to this? Getting this on Mac:

```
$ npx browserslist@latest --update-db
npx: installed 6 in 1.588s
Cannot read property '1' of null
```

**Comment by ai** [comment]
@Petah open a separate issue with full error message and your lock file to reproduce the error

**Comment by jeremyk** [comment]
@Petah - I think this might be because you don't have a browserlist entry in your package.json. I was seeing that error and that was the reason for me.

**Comment by Petah** [comment]
I figured it out, I had a pnpm lock file as well as a package lock which seemed to be confusing it. Deleting it fixed my issue.

**Comment by harshitsinghai77** [comment]
Deleting `yarn.lock` and then running `npm install` and then running `npx browserslist@latest --update-db` fixed the problem

**Comment by ai** [comment]
Do not delete `yarn.lock` because it will update all dependencies inside the project not only `caniuse-lite`

**Comment by igortas** [comment]
npx is creating package-lock file. Why there is no alternative version for npx browserlist --update-db?

**Comment by igortas** [comment]
> @BeisiXiong call it with `npx` even if you are using Yarn.
npx is creating package-lock file....

**Comment by ai** [comment]
@igortas maybe Yarn auto-detection has some issue.

`--update-db` supports both Yarn 1 and Yarn 3 versions.

Just be sure that you are calling it with `@latest` postfix:

```sh
npx browserslist@latest --update-db
```

**Comment by nickretallack** [comment]
Still broken for me

**Comment by KVROHITH098** [comment]
So I think we can open a PMR like a ticket and we can work from there s that cool. @isboas

**Comment by rwb196884** [comment]
This is still broken.

**Comment by emptyhere** [comment]
Still broken.

**Comment by 0biWanKenobi** [comment]
still broken on Windows and yarn as of today

**Comment by vishwajeet-graphy** [comment]
Still broken

**Comment by kuncevic** [comment]
> Still broken for me
> 
> ```
> node_modules/browserslist/update-db.js:49
>     if (match[1]) return match[1]
>              ^
> 
> TypeError: Cannot read property '1' of null
>     at getCurrentVersion (node_modules/browserslist/update-db.js:49:14)
>     at updateDB (node_modules/browserslist/update-db.js:119:17)
>     at Object.<anonymous> (node_modules/browserslist/cli.js:40:3)
>     at Module._compile (node:internal/modules/cjs/loader:1092:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
>     at Module.load (node:internal/modules/cjs/loader:972:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
>     at node:internal/main/run_main_module:17:47
> ```

I am on mac and this is broken too, getting an exact same error as above 👆

---

When do yarn install getting a warning below 👇

<img width="673" alt="Screenshot 2023-02-07 at 19 07 15" src="https://user-images.githubusercontent.com/1283734/217187435-ed9d0110-1a4e-4072-a4e1-6bd6ee45a7df.png">

Then trying a number of options to update browserslist

```
npx browserslist --update-db 
npx update-browserslist-db@latest 
npx browserslist@latest --update-db
```

Each attempt throws same error as above `TypeError: Cannot read property '1' of null`. 

Then tired to install `node_modules` using `npm` however it didn't help, getting same outcome`TypeError: Cannot read property '1' of null.` when trying to update `browserslist db`

My node version `16.17.1`

**Comment by kuncevic** [comment]
> Still broken for me
> 
> ```
> node_modules/browserslist/update-db.js:49
>     if (match[1]) return match[1]
>              ^
> 
> TypeError: Cannot read property '1' of null
>     at getCurrentVersion (node_modules/browserslist/update-db.js:49:14)
>     at updateDB (node_modules/browserslist/update-db.js:119:17)
>     at Object.<anonymous> (node_modules/browserslist/cli.js:40:3)
>     at Module._compile (node:internal/modules/cjs/loader:1092:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
>     at Module.load (node:internal/modules/cjs/loader:972:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
>     at node:internal/main/run_main_module:17:47
> ```

I am on mac and this is broken too, getting an exact same error as above 👆

---

When do yarn install getting a warning below 👇

<img width="673" alt="Screenshot 2023-02-07 at 19 07 15" src="https://user-images.githubusercontent.com/1283734/217187435-ed9d0110-1a4e-4072-a4e1-6bd6ee45a7df.png">

Then trying a number of options to update browserslist

```
npx browserslist --update-db 
npx update-browserslist-db@latest 
npx browserslist@latest --update-db
```

Each attempt throws same error as above `TypeError: Cannot read property '1' of null`. 

Then tired to install `node_modules` using `npm` however it didn't help, getting same outcome`TypeError: Cannot read property '1' of null.` when trying to update `browserslist db`

My node version `16.17.1`

**Comment by kuncevic** [comment]
@ai I am on mac

**Comment by ai** [comment]
@kuncevic why do you write in an issue about error in Windows?

**Comment by kuncevic** [comment]
@ai  it was quite similar issue at first sight, however I can create a new one

**Comment by ai** [comment]
Why do you need to open an issue if you already found that it was an environment problem?

> oh just installed npm modules with npm and seems work npx update-browserslist-db@latest

If you have any idea of improving DX, it is better to send PR. Open source is about collaboration.
