### ISSUE TITLE
Error message during browserslist database update

### ISSUE THREAD

**Issue by HummingMind** [browserslist/browserslist#704]
Hello.
When I run npx update-browserslist-db@latest or browserslist --update-db I get the error message saying:

-----------------------------------------------------
Cannot read properties of null (reading 'toString')

Problem with browser list retrieval.
Target browser changes won’t be shown.
-----------------------------------------------------

It seems like it still successfully updates caniuse-lite, but then shows the error at the end.
I can run browserslist and it shows the list of browsers just fine.

My config is:
"browserslist": "^4.21.0"

  "browserslist": [
    "last 2 versions",
    "not dead",
    "not op_mini all",
    "not and_qq 10.4",
    "not kaios 2.5",
    "not and_uc 12.12"
  ]

![image](https://user-images.githubusercontent.com/87399963/175148010-66c4b903-6257-4daf-87b5-0c2a164132f6.png)

Thank you.

**Comment by ai** [comment]
Thanks. I will try to update it later.

**Comment by ai** [comment]
The fix was released in 1.0.4. Please try new version by calling `npx update-browserslist-db@latest`.

**Comment by HummingMind** [comment]
Still get the same error:

![image](https://user-images.githubusercontent.com/87399963/175324376-0ee4ab1e-0182-490f-b24e-639ef89c1695.png)

**Comment by ai** [comment]
Hm. Have no idea why you haven’t better message.

Any way to reproduce the bug?

**Comment by HummingMind** [comment]
I see there are a few people who liked your initial response, so I figure they have the same error.
I don't think it's anything specific that I am doing.

I am on the latest current version of node and npm (not LTS). So, node is 18.4.0 and npm is 8.12.2.

I tried removing node cache and node_modules folders and that didn't help.

**Comment by ai** [comment]
I have the same stack.

Can you share your lock file?

**Comment by HummingMind** [comment]
[package-lock.json.txt](https://github.com/browserslist/browserslist/files/8971886/package-lock.json.txt)

**Comment by ai** [comment]
Still can’t reproduce. Can you find the file in npm cache and try to debug error.

Or you can just ignore the error. It is an error of showing the changes in browsers. `caniuse-lite` update still works.

**Comment by HummingMind** [comment]
I can take a look at the file. What's the file name that it is parsing through? I am a bit new to NPM and the JavaScript ecosystem world.

**Comment by HummingMind** [comment]
I tried this on another PC and did not get the error with the same project and toolset. It must be something specific to node being screwed up on my main PC. You can ignore this issue and thank you for looking into it! :beer: :thumbsup:

**Comment by HummingMind** [comment]
I somehow fixed it, but not sure what the exact fix was. It was either running cli.js in a terminal as an administrator, or it was adding the update-browserslist-db as a devDependency to my package.json. The error went away after one of these. 🥇 😄

**Comment by ai** [comment]
It maybe a `npx` cache issue.

**Comment by robincsamuel** [comment]
I had the same issue, and still have when I use npx. It worked when I added `update-browserslist-db` as a devDependency as @HummingMind  suggested and executed that.
